services:
  - type: web
    name: edutest-backend
    runtime: docker
    plan: starter
    region: frankfurt
    dockerContext: .
    dockerfilePath: ./src/Dockerfile
    healthCheckPath: /api/health
    disk:
      name: edutest-data
      mountPath: /app/data
      sizeGB: 1
    envVars:
      - key: APP_NAME
        value: Interactive Educational Tests Constructor
      - key: SECRET_KEY
        sync: false
      - key: TOKEN_TTL_HOURS
        value: "12"
      - key: DB_PATH
        value: /app/data/app.db
      - key: CORS_ORIGINS
        value: https://edutest-frontend.onrender.com

  - type: web
    name: edutest-frontend
    runtime: docker
    plan: starter
    region: frankfurt
    dockerContext: .
    dockerfilePath: ./frontend/Dockerfile
    envVars:
      - key: BACKEND_URL
        value: https://pircsp-cursach.onrender.com
